language: python
python:
  - "2.7"
  - "3.4"
install:
  - ./autogen.sh && python bootstrap.py && bin/buildout
  - python setup.py develop easy_install "sact.epoch[test]"
  - pip install coverage coveralls
script:
  - ./autogen.sh && python setup.py sdist --formats=gztar && pip install dist/sact.epoch-$(./autogen.sh --get-version | tr "_" "-").tar.gz --upgrade
  - bin/test
after_success:
  - coveralls
